### PR TITLE
Adjusts code structure and variable names

### PR DESCRIPTION
**Pull request by imminent**
Private methods and variables are implementation details, so I put them after public things which are the interface the user of the code interacts with.

### CODE REVIEW

**Comment by bauerca** [comment]
Hello. Thanks for this; I agree with your restructuring and would gladly merge. However, I am very close to merging the branch `slide_shuffle` into master. Since `slide_shuffle` is a somewhat major reworking of DSLV internals, I'd prefer to make the structural changes there. I can do this myself, unless you would like to. Let me know!

**Comment by imminent** [comment]
Oh, I see. What's the change in `slide_shuffle`?

**Comment by bauerca** [comment]
The slide_shuffle branch animates the drag-sort process. That is, the items underneath the floating view will slide around as they are resorted. I'm pretty pumped about it. :)

**Comment by imminent** [comment]
Wow, that's great. How close are you? What's left?

**Comment by bauerca** [comment]
Oh, mostly self-doubt at this point. Gonna test some more on my phone, then merge later today. Do you want to make another pull request after I merge, or should I do the restructuring myself?

**Comment by imminent** [comment]
If you have time you can do it. If not, I can do it again. I'm trying to figure out how to use this with a `CursorAdapter` I'm attempting to use a `CursorWrapper` that has a remapping of the positions (like you asked for position 4, that's actually position 7 now). And I'm thinking about having a wrapper class that can use the `DragSortListView` when on API < 11 and a Drag and Drop Framework version of it when on API >= 11. I think that's how things like ActionBarSherlock do it.

**Comment by bauerca** [comment]
That sounds good. I think a DnD Framework version of DSLV would be mostly trivial to implement (only the technique of drawing the floating view would change). Not sure what the immediate advantage is; but would be nice to be somewhat future-proofed. I guess customization of the floating view is a big advantage? I have plans to allow this for API < 11 though as well. I can open a public branch for this feature soon, if you'd like to contribute.

Closing this merge request. I'll copypasta some code around in the new commit per your restructuring suggestion.

**Comment by imminent** [comment]
Sounds good.

**Comment by bauerca** [comment]
Slide shuffling just merged into master FYI. Try it out!

**Comment by imminent** [comment]
Awesome, will look at it.

**Pull request closed without merging**
