### PR TITLE
Handle SLIDELEFT + rare crash

### PR DESCRIPTION
**Pull request by Tolriq**
Starting using Git for windows not sure I did correctly, and by seeing the patch of 15 lines changed to a full file update I'm pretty sure something goes wrong :)

But at least this permit the slideleft to work as slideleft and not trash, and updates the corresponding alpha + remove detection.

And correct a rare crash when getChildAt(0) returns null.

### CODE REVIEW

**Comment by bauerca** [comment]
Hey there. I think I see the addition in `onTouchEvent` for the slideleft thing, but I can't find your fix for the getChildAt crash. Can you explain the crash in more detail? Can you pinpoint a specific action that causes it? Thanks.

The weird diff may be a result of spaces vs tabbing issues? Not sure. Would be wonderful if you could redo the pull request and fix that, so that in the future, if we need to revisit any changes, we know where they occurred. To be honest, I don't think I can accept the request as is because of the extensive diff obfuscation.

I can work on a commit that converts all leading spaces to tabs and we can go from there...

**Comment by Tolriq** [comment]
Well I'll try to redo the diff, but in my client the diff was really showing 15 lines before commit.

I suppose this is a stupid bug of git for windows that may not handle correctly the end of line and changes \n to \r\n or something like that.

The changes for crash are : 

in dropFloatView 

```
            View v = getChildAt(0);
            int top = 0;
            if (v != null) {
                top = v.getTop();
            }
```

Since I don't know why but during some of my tests the getChildat(0) did return null.

For slide left there's 3 changes :

```
    private static final int FLING = 0;
    private static final int SLIDE = 1;
    private static final int SLIDELEFT = 2;
    private static final int TRASH = 3;
```

Since trash was using the value defined for slideleft in attributes.

in onTouchEvent 

```
                if (mRemoveMode == SLIDE && ev.getX() > r.right * 3 / 4) {
                    dropFloatView(true);
                } else if (mRemoveMode == SLIDELEFT && ev.getX() < r.right * 1 / 4) {
                    dropFloatView(true);
                } else {
                    dropFloatView(false);
                }

```

To correctly handle removal of items in move to the first 1/4 of the view.

in dragView

```
    if (mRemoveMode == SLIDELEFT) {
            float alpha = 1.0f;
            int width = mFloatView.getWidth();
            if (x < width / 2) {
                alpha = ((float) (x)) / (width / 2);
            }
            mWindowParams.alpha = alpha;
        }

```

To correctly handle alpha when sliding to left.

About things I'd like to add if possibility to swipe left right without reorder for starting actions.
But I don't know if this is in the scope of your class.

**Comment by Tolriq** [comment]
Ok now the PR should be near ok if you don't look how I arrived to it :p

**Comment by bauerca** [comment]
PR looks nice now except for that file .gitattributes; can you remove that? Also, maybe put your anti-crash code (in `dropFloatView()`) inside the if block that actually uses the `top` variable, i.e.

```
if (mSrcDragPos < firstPos) {
    // collapsed src item is off screen, no need to expand it; but, we
    // must adjust the scroll accordingly
    View v = getChildAt(0);
    int top = 0;
    if (v != null) {
        top = v.getTop();
    }
    setSelectionFromTop(firstPos - 1, top - getPaddingTop());
}
```

Thanks!

**Comment by Tolriq** [comment]
Moved the block from it's original place :)

For gitattributes this is mandatory on Windows to correctly handle EOL and not generate bad diff like before :)
I added this to .gitignore

**Pull request merged**
