### PR TITLE
Mavenize

### PR DESCRIPTION
**Pull request by schildbach**
Build DSLV with "mvn clean install"

Add DSLV to your project using this dependency:

`<dependency>
  <groupId>com.mobeta.android.dslv</groupId>
  <artifactId>drag-sort-listview</artifactId>
  <type>apklib</type>
  <version>1.0-SNAPSHOT</version>
 </dependency>`

### CODE REVIEW

**Comment by schildbach** [comment]
I've updated my pull request by an optional dependency to the android support package, as some classes in drag-sort-listview now need it.

**Comment by schildbach** [comment]
I wonder how I can change the branch name of this pull request. Since I'll be using "master" to add more commits (not part of this pull request), I'd like to switch the branch of this pull request to "mavenize".

Alternatively, just pick eee66b39b46172a6135efd4a9c8376349fe24ec6 from master.

**Comment by bauerca** [comment]
Hey Andreas,

Sorry for the uber-late reply; been busy. I am working on the "mavenize" tonight. TODO:
1. pull your eee66b3 and get v4 support working
2. write up install instructions for mavenites

I'm still new to maven, but having fun learning! Thanks, and I'll keep you posted.

**Comment by bauerca** [comment]
One comment on the pom. Do you think it would be better to use the dependencies specified in https://github.com/mosabua/maven-android-sdk-deployer ? I know it's another kink in the whole process, but should be no problem for the basic maven user right?

I personally like the deployer method because it encourages use of the most recent revisions from android (e.g. rev. 10 of the v4 compat instead of rev. 7 from maven central)

**Comment by schildbach** [comment]
I decided against using maven-android-sdk-deployer in all my projects, because its another complicated step for new users. Also, you will never get your artifact (drag-sort-listview that is) accepted in Maven Central, because maven-android-sdk-deployer artifacts are not in there afaik.

The two Android dependencies are for linking only anyway. There is nothing wrong with making sure your code works with old versions of SDKs and libraries. In fact, this is a desired property of any library. The user of your library will be able to pick a later version if he decides.

**Comment by schildbach** [comment]
Looking at the pom again, I realized that we should synchronize the Android dependency with targetSdk from the manifest. Which means version 2.1 (API level 7). I'll see if that works.

**Comment by schildbach** [comment]
I just rebased (all my pull requests) against your master and changed the Android dependency to version 2.1_r1.

The commit to cherry-pick would now be 36c5eda480fef8a3327b1b6239e0776350ca560e.

**Comment by bauerca** [comment]
Okay that's fine for the android.jar, because that is given to you by your device/emulator. What about the compat lib though? The android compat library must be included in an apk's libs. Your pom chooses compat-r7 as the dependency. So I must assume that when deploying, maven pulls in the compat-r7.jar to package the apk. If the dev's app (which depends on dslv) requires some features from compat-r10, then both will be pulled in, correct? That seems like a waste. Now the dev has to go through extra complicated steps anyway to correct this. Forgive my ignorance of maven (if I'm wrong :)).

**Comment by schildbach** [comment]
Maven will make sure you've only got one version of the same artifact in your final build. POMs nearer to the root of the dependency tree have priority.

I declared the support package as optional because of two reasons:

1) There is only one class in drag-sort-listview using it and usage of that class is entirely optional.

2) In the special case of the support package, there are not only different versions of the same artifact (r7, r10) but also two different flavors targetted at different API levels (v4, v11). Those flavors were put into Maven central as different artifacts so Maven will not detect collisions between them. If the artifact would not be declared as optional, the problem from your last comment could become valid and you'd end up with two artifacts having the same classes.

**Comment by bauerca** [comment]
> Maven will make sure you've only got one version of the same artifact in your final build. POMs nearer to the root of the dependency tree have priority.

Interesting. That implies an assumption of backward compatibility for an artifact (not saying that's a bad thing).

> 1) There is only one class in drag-sort-listview using it and usage of that class is entirely optional.

Agreed.

> 2) In the special case of the support package, there are not only different versions of the same artifact (r7, r10) but also two different flavors targetted at different API levels (v4, v11). Those flavors were put into Maven central as different artifacts so Maven will not detect collisions between them. If the artifact would not be declared as optional, the problem from your last comment could become valid and you'd end up with two artifacts having the same classes.

Which would, in fact, be necessary, since DSCursorAdapter imports android.support.v4 stuff. In other words, the dev would have to change the DSCursorAdapter source to get rid of the v4 dependency.

Thanks for the mini maven lesson. I will go ahead and push changes soon. I'm reorganizing the root dir into demo/ library/ tools/ and adding a parent pom that will build both the library and demo project. Would be nice if you could check my work when it's done.

-Carl

**Comment by bauerca** [comment]
Okay maven stuff has been pushed. Because of the branching issue here, I have to close the pull request instead of officially merging, even though I did merge from your forked repo.

**Pull request closed without merging**
