### PR TITLE
Updated documentation and naming

### PR DESCRIPTION
**Pull request by imminent**
I started going through the lastest version of the DSLV. I still haven't covered most of the code yet.

### CODE REVIEW

**Comment by imminent** [comment]
@bauerca I just went through all the code, I merged in the change from the issue with the `0.5f`. I saw there were a lot more comments in the code this time, that was pretty helpful.

**Comment by imminent** [comment]
fun fact, I think a calculation is messed up in my code (works fine in yours). You understand it better, maybe you know where I missed something, but the float view (drag shadow) doesn't get generated at the touch position, it starts to the right and above or below depending on the selected item's position. Other than that it seems to still work.

**Comment by bauerca** [comment]
I thought this was a renaming/documentation update. I'll have to take a look later tonight. Btw, I've done some drag-scroll calculations wrong in the version you are updating. We'll have some signif conflicts... :)

**Comment by bauerca** [comment]
Okay. Sorry, but I kinda bypassed this one. I just committed changes with consistent tabbing mimicking the standard inferred from android's ListView. Hope it's cleaner for ya.

I'm gonna keep the naming as is for a bit, due to the complexity of some of the if/else trees. :P

**Pull request closed without merging**
