### PR TITLE
add support for remove handle

### PR DESCRIPTION
**Pull request by schildbach**
I have the requirement to add a button for removing list items (rather than using the gestures). I figured it might be handy to - similar to dslv:drag_handle_id - define a dslv:remove_handle_id in your listview that causes clicks on that handle to call DropListener.drop(pos, pos+1).

Have a look at my implementation. I'm not sure if the logic should actually go into DragSortController. However, I figured that would need some more callbacks etc. so I took the easy path in a first shot.

### CODE REVIEW

**Comment by bauerca** [comment]
Sounds great. As you say I think this should go in the DSController, with xml access in the dslv layout of course.

Also I've been learning about maven and will merge your poms soon. Been traveling quite a bit...

**Comment by imminent** [comment]
I would almost say it's outside of the drag sort role since it's a click,
there is not dragging happening, which isn't the same as the drag handle.
Calling it a remove handle is misleading as handle refers to some you use
to "pull" something else that it is "attached" to in some way.

**Comment by bauerca** [comment]
The DragSortController is just a bunch of convenience stuff, so I think it would be okay to put a convenience click removal technique in there (since this seems common enough; I prefer a delete button rather than a fling remove myself). As Dandre' points out, I think it should be called something like `remove_id` or `item_remove_id` (better suggestions please!).

I think I'll add a method to DSLV called `removeItem(int position)` which simply calls through to the RemoveListener, if one exists (so that removal does not have to go through the drag process). In fact, why not add call-thru for `moveItem(int from, int to)` as well? Expanding the role of DragSortListView to SortListView, or OrganizeListView or something...

**Comment by imminent** [comment]
Sounds good Carl. Advanced approach would be the swipe to reveal remove
button, then click remove button to remove item (ala iOS), but I don't
believe that's standard Android design. Useful if it isn't feasible to make
the removal easily reversible or if the items are very valuable to the
user. maybe `remove_action_id` or `remove_action_view`?

**Comment by bauerca** [comment]
Okay, this convenience is now in the DragSortController class. Check out the new xml attrs.

**Comment by schildbach** [comment]
Thanks, I just adapted my project to it and it works (and looks nice, because of the new remove animation).

**Pull request closed without merging**
