### PR TITLE
Fix another rare crash

### PR DESCRIPTION
**Pull request by Tolriq**

### CODE REVIEW

**Comment by bauerca** [comment]
Hm, another `getChildAt(0)` crash. Is it possible your ListAdapter is getting refreshed during a drag-sort? Or some other reason your ListAdapter might return a count of 0 during a drag-sort?

The fix seems mostly harmless, so I'll merge it; I'm just trying to understand what's happening here as I have not been able to reproduce these crashes. Thanks for the contributions!

**Comment by Tolriq** [comment]
The list should not refresh and I can't reproduce either but my app is published in Play Store and I get some very rare crashes report.

BTW securing those calls does not arm and can save some crashes :)

**Comment by bauerca** [comment]
Okay thanks. BTW, what's the name of your app?

**Comment by Tolriq** [comment]
Yatse Widget.

https://play.google.com/store/apps/details?id=org.leetzone.android.yatsewidgetfree

**Pull request merged**
