### PR TITLE
Code cleanup to consistently use 4 spaces (instead of tabs).

### LINKED ISSUE #5: Source code has a mix of spaces and tabs
The source has a mix of tabs and spaces. If you use an editor that has a tab length other than 2, it makes the source much harder to read.

### PR DESCRIPTION
**Pull request by theelfismike**
Fix #5 to consistently use 4 spaces for indentation.

### CODE REVIEW

**Comment by bauerca** [comment]
Your pull request modifies old, buggy code. I fixed the tabs/spaces issue on my own. As per your suggestion, 4 spaces is now the standard. As for the rest, I am now trying to conform to the standards as I have inferred them from android's ListView code; i.e. tabs expanded to 4 spaces, 2 tabs (4 spaces) for line continuation, space between "if" and "(expression)", "} else {", etc. Thanks.

**Comment by theelfismike** [comment]
My changes modified master from yesterday morning... Not sure what you mean?

I would suggest you set up Eclipse/IntelliJ with the code format you want to use, and have it automatically refactor it for you periodically.

**Comment by bauerca** [comment]
Check out the history: https://github.com/bauerca/drag-sort-listview/network

My commit that slid in front of yours (fixing #26 and other stuff) was a pretty major update, eliminating jumpy behavior and simplifying a pretty tricky calculation. After your request came in, I pulled it to a local branch and tried the merge. Since the formatting update changes every line, it was quite tough to go through and correct the algorithm updates. It was much easier just to change the tab/spacing issue myself with a clean copy.

I appreciate the help and advice, and would love to see your future improvements. Thanks.

**Comment by theelfismike** [comment]
Cool, that makes sense.

**Pull request closed without merging**
